version: 1
disable_existing_loggers: true



formatters:
    standard:
        format: "%(asctime)s - %(name)-10s - %(levelname)-8s - %(lineno)3d - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: routeTracker.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [file_handler]
    propagate: yes

loggers:
    LogReader:
        level: DEBUG
        handlers: [file_handler]
        propagate: no

    UserInterface:
        level: DEBUG
        handlers: [file_handler]
        propagate: no